checks:
    javascript:
        vars_on_top: true
        wrap_iife: true
        wrap_regex: true
        yoda:
            setting: 'Disallow Yoda Conditions'
        valid_typeof: true
        valid_jsdoc: true
        use_isnan: true
        space_return_throw_case: true
        radix: true
        one_var: true
        no_wrap_func: true
        no_with: true
        no_void: true
        no_use_before_define: true
        no_unused_vars: true
        no_unused_expressions: true
        no_unreachable: true
        no_underscore_dangle: true
        no_undefined: true
        no_undef_init: true
        no_undef: true
        no_trailing_spaces: true
        no_ternary: true
        no_sparse_arrays: true
        no_sync: true
        no_space_before_semi: true
        no_shadow_restricted_names: true
        no_shadow: true
        no_sequences: true
        no_self_compare: true
        no_script_url: true
        no_return_assign: true
        no_reserved_keys: true
        no_redeclare: true
        no_proto: true
        no_process_exit: true
        no_process_env: true
        no_plusplus: true
        no_path_concat: true
        no_octal_escape: true
        no_octal: true
        no_obj_calls: true
        no_new_wrappers: true
        no_new_require: true
        no_new_object: true
        no_new_func: true
        no_new: true
        no_nested_ternary: true
        no_negated_in_lhs: true
        no_native_reassign: true
        no_multi_str: true
        no_mixed_spaces_and_tabs: true
        no_loop_func: true
        no_lonely_if: true
        no_lone_blocks: true
        no_labels: true
        no_label_var: true
        no_iterator: true
        no_irregular_whitespace: true
        no_invalid_regexp: true
        no_inner_declarations: true
        no_inline_comments: true
        no_implied_eval: true
        no_func_assign: true
        no_floating_decimal: true
        no_fallthrough: true
        no_extra_strict: true
        no_extra_semi: true
        no_extra_boolean_cast: true
        no_extra_bind: true
        no_extend_native: true
        no_ex_assign: true
        no_eval: true
        no_eq_null: true
        no_empty_label: true
        no_empty_class: true
        no_empty: true
        no_else_return: true
        no_dupe_keys: true
        no_div_regex: true
        no_delete_var: true
        no_debugger: true
        no_control_regex: true
        no_constant_condition: true
        no_console: true
        no_comma_dangle: true
        no_caller: true
        no_catch_shadow: true
        no_bitwise: true
        no_array_constructor: true
        no_alert: true
        new_parens: true
        new_cap: true
        max_len:
            max_length: '120'
        guard_for_in: true
        eqeqeq: true
        eol_last: true
        dot_notation: true
        default_case: true
        curly: true
        consistent_this: true
        consistent_return: true
        comma_style:
            style: 'At the end of the line'
        camelcase: true
        block_scoped_var: true
    php:
        code_rating: true
        duplication: true
        remove_extra_empty_lines: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: true
        fix_line_ending: true
        return_doc_comments: true
        parameter_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        param_doc_comment_if_not_inferrable: true
        more_specific_types_in_doc_comments: true
        no_goto: true
        uppercase_constants: true
        simplify_boolean_return: true
        properties_in_camelcaps: true
        prefer_while_loop_over_for_loop: true
        parameters_in_camelcaps: true
        optional_parameters_at_the_end: true
        newline_at_end_of_file: true
        line_length:
            max_length: '120'
        function_in_camel_caps: true
        classes_in_camel_caps: true
        avoid_todo_comments: true
        avoid_perl_style_comments: true
        avoid_fixme_comments: true
        align_assignments: true
        use_self_instead_of_fqcn: true
        phpunit_assertions: true
        avoid_multiple_statements_on_same_line: true
        avoid_unnecessary_concatenation: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
        braces:
            classes_functions:
                class: new-line
                function: new-line
                closure: end-of-line
            if:
                opening: end-of-line
            for:
                opening: end-of-line
            while:
                opening: end-of-line
            do_while:
                opening: end-of-line
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower

tools:
    php_cs_fixer:
        config: { level: all }

build:
    dependencies:
        before:
            - sudo apt-get install -y software-properties-common
            - sudo add-apt-repository -y ppa:ondrej/php5
            - sudo ln -s $(pwd) /vagrant
            - curl -sL https://deb.nodesource.com/setup | sudo bash -
            - sudo apt-get install -y build-essential php5-fpm nginx nodejs
            - sudo npm install -g zombie
            - sudo cp provisioning/nginx-sites/test /etc/nginx/sites-enabled/default
            - sudo ln -s $(pwd) /vagrant
            - sudo service nginx restart
    environment:
        php:
            version: 5.5.12
            ini:
                'date.timezone': 'UTC'
        hosts:
            weather-app: '127.0.0.1'
            test.weather-app: '127.0.0.1'
            dev.weather-app: '127.0.0.1'
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'php-clover'
            -
                command: 'NODE_PATH=/usr/lib/node_modules vendor/bin/behat'
